### ISSUE TITLE
Getting 404 while exchanging public_token for access_token

### ISSUE THREAD

**Issue by sudeeptarlekar** [plaid/plaid-node#156]
I am using Plaid for first time.

Trying to integrate Plaid in my React app and getting `public_token` from `react-plaid-link`, but while exchanging `public_token` for `access_token` plaidClient giving error 404.

This is how I am handling `onSuccess` event of `react-plaid-link` to get `access_token`

```
import plaid from 'plaid';

handleOnSuccess = (publicToken, metadata) => {
  const plaidClient = new plaid.Client(clientId, secret, publicKey, plaid.environments.sandbox);
  plaidClient.exchangePublicToken(publicToken)
    .then(response => console.log('Successful response : ', response))
    .catch(error => console.log('Error while fetching access token : ', error));
}
```
Code above giving error `OPTIONS https://sandbox.plaid.com/item/public_token/exchange 404 (Not Found)`, what am I doing wrong here?

**Comment by sudeeptarlekar** [comment]
Got this working by method mentioned in issue #72.

**Comment by aldeka** [comment]
I'm running into this same issue. I don't understand how plaid-node's request can 404 when made from the frontend but work fine when made from the backend. It's the same library being imported, and the same JS code!

I'm using create-react-app to do my experiment, so I'm really not supposed to be mucking around in the minimal backend code used to serve the application. I get that if this were anywhere near a prod-type app, you'd want to run the calls through the backend (for retry value when plaid is slow or gone, and also because you can't just turn off CORS in prod). But for experimentation--I just don't understand why the behavior would be different.
