### ISSUE TITLE
UnsetVariableError: No environment variable named "5be9e149ec24fd001207d4a8"

### ISSUE THREAD

**Issue by bleenk** [plaid/plaid-node#178]
Please I need help in resolving this. 
nsetVariableError: No environment variable named ""C:\Users\The Beast\Desktop\Plaidruby\quickstart\node\node_modules\envvar\index.js:39
     throw createUnsetVariableError(name);       ^ UnsetVariableError: No environment variable named "5be9e149ec24fd001207d4a8"

**Comment by ssmucker** [comment]
I'm having this exact same problem. I'm trying to run the Node quickstart straight out of the box, and the only things I've changed in the index.js file are the client ID, secret, and public key environmental variables. I'm getting the same error as bleenk when I run index.js (except for my client ID instead of theirs).

**Comment by Kahaan** [comment]
Had the same issue, realized that all you have to do is add the credential as the second argument for the envar.string() function. For example -

var PLAID_CLIENT_ID = envvar.string(
  "PLAID_CLIENT_ID",
  "5be9e149ec24fd001207d4a8"
)

That seemed to do the trick for me. Hope this helps!
