### ISSUE TITLE
getWebhookVerificationKey typescript definition is incorrect

### ISSUE THREAD

**Issue by scottypickering** [plaid/plaid-node#251]
The `getWebhookVerificationKey` typescript definition appears to be incorrect.

The current definition requires a callback but returns a promise:
```
// getWebhookVerificationKey(String, String)
getWebhookVerificationKey(
    key_id: string,
    cb: Callback<WebhookVerificationKeyResponse>,
): Promise<WebhookVerificationKeyResponse>; 
```

To enable use with async/await I believe these should be the typescript definitions:
```
// getWebhookVerificationKey(String, Function)
getWebhookVerificationKey(
    key_id: string,
    cb: Callback<WebhookVerificationKeyResponse>,
): void;

// getWebhookVerificationKey(String)
getWebhookVerificationKey(
  key_id: string
): Promise<WebhookVerificationKeyResponse>;
```

**Comment by isparling** [comment]
Bumping this; typings still don't allow function to be invoked without a callback as of release 4.11

**Comment by ablankenship10** [comment]
Also encountering this issue, using the getWebhookVerificationKey(kid) using await rather than a callback, it crashes my server despite being inside a try/catch somehow. Also would prefer if this function could handle the complete validation of the value of the webhook `Plaid-Verification` header, rather than JWT parsing it, validating the `alg` value and then passing the `kid` value to this function to verify. Ideally I would pass the JWT string from the header and the post body (optionally) for it to handle parsing, validating the token as well as the sha256 signature for the body.

**Comment by skylarmb** [comment]
hello there, ive created #293 

Reminder that PRs are always welcome :)

**Comment by skylarmb** [comment]
#293 was merged!
