### ISSUE TITLE
plaid-ios crash (why does iOS have no issues tab)

### ISSUE THREAD

**Issue by mlfarrell** [plaid/plaid-node#404]
Tell me where to go to raise this issue and i'll close and repost.

I need to know which plaid iOS version fixes this crash (if any)
We started seeing it recently.

```NSInvalidArgumentException
*** -[__NSCFString rangeOfString:options:range:locale:]: nil argument```

```
CoreFoundation | __exceptionPreprocess (CoreFoundation)
-- | --
libobjc.A.dylib | objc_exception_throw (libobjc.A.dylib)
Foundation | -[NSPathStore2 copyWithZone:] (Foundation)
LinkKit | 0x102410000 + 384188
LinkKit | 0x102410000 + 383080
LinkKit | 0x102410000 + 187316
LinkKit | 0x102410000 + 181524
libdispa...ch.dylib | _dispatch_call_block_and_release (libdispatch.dylib)
libdispa...ch.dylib | _dispatch_client_callout (libdispatch.dylib)
libdispa...ch.dylib | _dispatch_main_queue_callback_4CF$VARIANT$armv81 (libdispatch.dylib)
CoreFoundation | __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ (CoreFoundation)
CoreFoundation | __CFRunLoopRun (CoreFoundation)
CoreFoundation | CFRunLoopRunSpecific (CoreFoundation)
GraphicsServices | GSEventRunModal (GraphicsServices)
UIKitCore | -[UIApplication _run] (UIKitCore)
UIKitCore | UIApplicationMain (UIKitCore)
```

**Comment by skylarmb** [comment]
Hello, plaid-link-ios does not have an issues tab because we would prefer if you filed a support ticket. You will get a faster response, better technical expertise to solve your issue, and it allows us to track and prioritize your issue in our internal systems.

https://dashboard.plaid.com/support/new/product-and-development/developer-lifecycle/link
