### ISSUE TITLE
Plaid `/item/get` error type is using default Javascript Error class

### ISSUE THREAD

**Issue by dan-cooke** [plaid/plaid-node#532]
The expected type for the `error` on this response is the following object:

<img width="631" alt="image" src="https://user-images.githubusercontent.com/22816887/182178693-b0c06c83-cc0e-48cf-a703-82c676b7bae8.png">

AS documented here https://plaid.com/docs/api/items/#item-get-response-item-error

But the actual type in the plaid node client library is

<img width="631" alt="image" src="https://user-images.githubusercontent.com/22816887/182178821-7dd6bc59-6b1e-4891-a6b6-9876bba57ea1.png">

`plaid: 10.8.0`

**Comment by phoenixy1** [comment]
Thanks for the heads up! It looks like the library is incorrectly using the Error type instead of the PlaidError type here. I have put together a PR to fix this -- unfortunately it will looks like it will juuuust miss the August client library release but will go out in the September one. If this issue is blocking you / you desperately need a hotfix, let us know and we'll see what we can do.

**Comment by dan-cooke** [comment]
@phoenixy1 that’s great thank you! No it’s not blocking I’ve just imported the type and cast to it in the meantime

**Comment by phoenixy1** [comment]
@dan-cooke cool! I just merged the PR that will resolve this once the client library is generated from it, so I'm going to close this out. Feel free to re-open if it's not fixed in the September release.
