### ISSUE TITLE
linkTokenCreate() does not work

### ISSUE THREAD

**Issue by JVMartin** [plaid/plaid-node#563]
Per the docs here:
https://plaid.com/docs/api/tokens/#linktokencreate

We are NOT supposed to hand any products into the `products` array if all we want is balance:

> balance is not a valid value, the Balance product does not require explicit initialization and will automatically be initialized when any other product is initialized.

However, using the code as described does not work. Any request missing the `products` array:
```typescript
const response = await client.linkTokenCreate({
  user: {
    client_user_id: '1',
  },
  client_name: 'My Company',
  language: 'en',
  country_codes: [CountryCode.Us],
});
```

Results in this 400 response body:
```json
{
  "display_message": null,
  "documentation_url": "https://plaid.com/docs/?ref=error#invalid-request-errors",
  "error_code": "INVALID_FIELD",
  "error_message": "must provide at least one product",
  "error_type": "INVALID_REQUEST",
  "request_id": "<redacted>"
}
```

How are we supposed to get balance then?

This is really an issue with the API and not the SDK, but I'm not sure where to file an issue with the API.

**Comment by JVMartin** [comment]
I've also created a Plaid support case, since this is really an API issue:
https://dashboard.plaid.com/support/case/484001

**Comment by phoenixy1** [comment]
@JVMartin I see your issue was resolved over Zendesk, but for the record / other folks who see this ticket, Plaid only offers Balance as essentially an add-on product, it doesn't support using only the balance product and no other products. 

So this is really the side effect of how Plaid bundles / sells its products -- adding other products to the Item to make Balance work will have billing implications, as you will be charged for those products when you add them. The API reflects the fact that there is no way to only purchase access to Balance without also purchasing access to another Plaid product. I'll update the docs to make that explicit.
