### ISSUE TITLE
Healthcheck endpoint for Plaid API

### ISSUE THREAD

**Issue by vinitshahdeo** [plaid/plaid-node#594]
## Issue Summary

I'm seeking assistance in finding a reliable method to assess the **health status of the Plaid API**.

## Workaround

One potential workaround involves retrieving the account ID, but I'm concerned about the associated API usage costs and pricing implications. I'm interested in discovering the optimal approach for evaluating the operational health of the Plaid API.

```javascript
const response = await plaidClient.accountsGet({
  access_token,
  options: {
    account_ids: ['123456790'],
  },
});
```

**Comment by phoenixy1** [comment]
The correct answer to this is going to depend on what you mean by the operational health of the API, since there are a number of different dimensions to that. 

Plaid has a couple of existing methods for assessing health, including

[API status reporting](https://plaid.com/docs/api/#api-status-and-incidents)
Item Health Data, accessible via the [API](https://plaid.com/docs/api/items/#itemget) or the [Dashboard](https://dashboard.plaid.com/activity/debugger)
Institution Health Data, accessible via the [API](https://plaid.com/docs/api/institutions/#institutionsget_by_id) or [Dashboard](https://dashboard.plaid.com/activity/status).

More details in the docs: https://plaid.com/docs/account/activity/
