### ISSUE TITLE
Force transactions_sync endpoint to return historical data.

### ISSUE THREAD

**Issue by sleep9** [plaid/plaid-node#636]
From the documentation 

> **In the first call** to [/transactions/sync](https://plaid.com/docs/api/products/transactions/#transactionssync) for an Item, the endpoint will return **all historical transactions** data associated with that Item up until the time of the API call (as "adds"), which then generates a next_cursor for that Item. In subsequent calls, send the next_cursor to receive only the changes that have occurred since the previous call.

However when I call transactions sync for the first time (with next_cursor not present) after linking the accounts I receive INITIAL_UPDATE_COMPLETE and only 30 days of transactions.

Is there a way to force the endpoint to return historical transactions when first linking to the account? I would like to avoid using webhooks if neccessary.

**Comment by phoenixy1** [comment]
There is not a way to keep the initial transaction pull from being broken into two parts (historical and initial). If you don't want to wait for the webhook, I suppose you could just wait for a few minutes before calling the sync endpoint to have really good odds that the fetch is complete. However, we STRONGLY encourage you to implement webhooks, since they are pretty core to how Plaid handles async behaviors, and the Plaid API has a lot of async behaviors, especially when using the transactions endpoints.

**Comment by sleep9** [comment]
Thanks for your reply... I cant seem to find in the documentation how/where to declare the webhook url programmatically for transactions. It seems as though I need to proceed with webhook approach. 

Its unfortunate that historical data is not readily available. Even with a debounce + poll it still returns initial.

**Comment by phoenixy1** [comment]
Closing this out as it's not related to the node client library -- if you continue to have trouble, feel free to file a support ticket
