### ISSUE TITLE
Add zero_hash to ProcessorTokenCreateRequestProcessorEnum

### ISSUE THREAD

**Issue by Only1MrAnderson** [plaid/plaid-node#639]
The Plaid documentation lists `zero_hash` as a processor but it is missing from the ProcessorTokenCreateRequestProcessorEnum

[Stripe Docs](https://plaid.com/docs/api/processors/#processortokencreate)
<img width="590" alt="Screenshot 2024-06-24 at 3 14 49 PM" src="https://github.com/plaid/plaid-node/assets/8826208/53949644-6493-41e3-ba10-694588c96465">

**Comment by phoenixy1** [comment]
It's there...I can't link the line number because the file is too large for GitHub to display, but if you go to https://raw.githubusercontent.com/plaid/plaid-node/master/dist/api.js and command-F for 
`ProcessorTokenCreateRequestProcessorEnum["ZeroHash"] = "zero_hash";` you'll see it. If you can't access it, you may need to upgrade to the latest version of the client library
