### ISSUE TITLE
InstitutionsGetByIdRequestOptions is out of date

### ISSUE THREAD

**Issue by tylerkatz** [plaid/plaid-node#650]
This TS type is missing the `include_display_data` field, which I happened to need for an app.  Not sure if this field is also missing from other types but it's missing here while supported in the API (checked via Postman)

Thanks!

**Comment by phoenixy1** [comment]
@tylerkatz this is by design -- the current client library supports only the 2020-09-14 version of the Plaid API, and the `include_display_data` field was removed in that API version. For context, `include_display_data` field is a legacy, undocumented, and unsupported field. If you need the functionality provided by this field, we recommend contacting your Plaid Account Manager for options.

**Comment by tylerkatz** [comment]
@phoenixy1 Got it.  I see in the docs (and the type definition) that the correct option is `include_optional_metadata` which seems to include the same logo info.  Closing.  Thanks.
